# first create network centrex with `docker network create centrex`
version: "3.9"

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - centrex
    volumes:
      - CeNTREX_influxdb:/var/lib/influxdb
      - CeNTREX_influxdb:/var/lib/influxdb2
      - CeNTREX_influxdb:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=
      - DOCKER_INFLUXDB_INIT_PASSWORD=
      - DOCKER_INFLUXDB_INIT_ORG=CeNTREX
      - DOCKER_INFLUXDB_INIT_BUCKET=environment
      - DOCKER_INFLUXDB_INIT_RETENTION=104w
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - centrex
    volumes:
      - CeNTREX_grafana:/var/lib/grafana:rw
    environment:
      - GF_SECURITY_ADMIN_USER=
      - GF_SECURITY_ADMIN_PASSWORD=
    depends_on:
      - influxdb
networks:
  centrex:
volumes:
  CeNTREX_influxdb:
  CeNTREX_grafana: