apiVersion: 1
datasources:
  - name: InfluxDBEnvironment
    type: influxdb
    access: proxy
    database: environment
    user: grafana
    password: molecules
    url: http://influxdb:8086
    isDefault: true
    editable: true
